### ISSUE TITLE
Substitution model in Shmulate 

### ISSUE THREAD

**Issue by Egl-A** [cran/shazam#1]
Hi, 
I wondered if Shazam package was able to take into account mismatch repair on top of single nucleotide substitution (notably with the shmulateSeq function). 
Thank you in advance for your help !

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
